### ISSUE TITLE
雀魂信息查询报错

### ISSUE THREAD

**Issue by Mei-Sakura** [DaiShengSheng/Majsoul_bot#1]
_int_.py中majsoulInfo指令中的  message = "\n"   位置错误，导致getID错误
![image](https://user-images.githubusercontent.com/81066884/120063895-12eec080-c09c-11eb-8eb1-fbb46e466c44.png)

**Comment by Mei-Sakura** [comment]
正确的如上，作者改一下项目吧

**Comment by DaiShengSheng** [comment]
已知晓，今天更新新功能后一并更改
