### ISSUE TITLE
刚使用一次就回答超时

### ISSUE THREAD

**Issue by BlackTitle** [DaiShengSheng/Majsoul_bot#2]
使用了第一次查询能够搜出来
第二次及之后就超时，是我服务器的问题还是啥
对话如下:
三麻信息 QAQ受害者
获取牌谱屋的数据超时了呢，请稍后再试哦~

**Comment by DaiShengSheng** [comment]
牌谱屋的接口有些时候不是很稳定，偶尔会有超时的情况
