### ISSUE TITLE
安装成功但是一直答复获取牌谱屋的数据超时

### ISSUE THREAD

**Issue by xia0ti** [DaiShengSheng/Majsoul_bot#3]
大佬您好，我不是很懂python。按照教程装好了bot。在群聊里使用lssv，可以正常显示
|○| 雀魂信息查询
|○| 雀魂对局订阅
|○| 雀魂帮助
输入雀魂帮助也能得到帮助命令。
但是使用帮助命令时一直反馈获取牌谱屋的数据超时，一次都未成功过。
请问是否有可能是我的配置或者安装错误导致的，还是单纯换一个时间再尝试就可以了。
非常感谢！

**Comment by DaiShengSheng** [comment]
看一下截图，如果命令格式没有问题的话，换个时间尝试就可以了。

**Comment by xia0ti** [comment]
非常感谢，我再试一下吧。打扰您了
